[tool.poetry]
name = "rddl_instance_generator"
version = "0.1.0"
description = ""
authors = ["GMMDMDIDEMS"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyrddlgym = "^2.0"
ipykernel = "^6.29.5"
numpy = "1.26.4"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
