name: "UAV"
domain_alias: "kinematic_UAVs_con"

# Domain types
types:
  - name: aircraft
    kind: object
    alias: a

# Non-fluent variables
non_fluents:
  - name: CONTROLLABLE
    type_value: bool
    default: false
    sampling_range:
      min: 0.1
      max: 0.5

  - name: GRAVITY
    type_value: float
    default: 9.8
    sampling_range:
      min: 9.8
      max: 9.8

  - name: MIN-X
    type_value: float
    default: -50000.0
    sampling_range:
      min: -50000.0
      max: -50000.0

  - name: MAX-X
    type_value: float
    default: 50000.0
    sampling_range:
      min: 50000.0
      max: 50000.0

  - name: MIN-Y
    type_value: float
    default: -50000.0
    sampling_range:
      min: -50000.0
      max: -50000.0

  - name: MAX-Y
    type_value: float
    default: 50000.0
    sampling_range:
      min: 50000.0
      max: 50000.0

  - name: MIN-Z
    type_value: float
    default: -50000.0
    sampling_range:
      min: -50000.0
      max: -50000.0

  - name: MAX-Z
    type_value: float
    default: 50000.0
    sampling_range:
      min: 50000.0
      max: 50000.0

  - name: SCALE-FACTOR
    type_value: float
    default: 0.1
    sampling_range:
      min: 0.1
      max: 0.1

  - name: RANDOM-WALK-COEFF
    type_value: float
    default: 0.1
    sampling_range:
      min: 0.1
      max: 0.1

  - name: VEL-REG
    type_value: float
    default: 0.001
    sampling_range:
      min: 0.001
      max: 0.001

  - name: MIN-ACC
    type_value: float
    default: -1.0
    sampling_range:
      min: -10.0
      max: -1.0

  - name: MAX-ACC
    type_value: float
    default: 1.0
    sampling_range:
      min: 1.0
      max: 1.0

  - name: MIN-DELTA-PHI
    type_value: float
    default: -1.0
    sampling_range:
      min: -1.0
      max: -1.0

  - name: MAX-DELTA-PHI
    type_value: float
    default: 1.0
    sampling_range:
      min: 1.0
      max: 1.0

  - name: MIN-DELTA-THETA
    type_value: float
    default: -1.0
    sampling_range:
      min: -1.0
      max: -1.0

  - name: MAX-DELTA-THETA
    type_value: float
    default: 1.0
    sampling_range:
      min: 1.0
      max: 1.0

  - name: GOAL-X
    type_value: float
    default: 100.0
    sampling_range:
      min: 100.0
      max: 100.0

  - name: GOAL-Y
    type_value: float
    default: 100.0
    sampling_range:
      min: 100.0
      max: 100.0

  - name: GOAL-Z
    type_value: float
    default: 100.0
    sampling_range:
      min: 100.0
      max: 100.0

# State-fluent variables
state_fluents:
  - name: pos-x
    type_value: float
    default: 0.0
    sampling_range:
      min: 0.0
      max: 50000.0

  - name: pos-y
    type_value: float
    default: 0.0
    sampling_range:
      min: 0.0
      max: 50000.0

  - name: pos-z
    type_value: float
    default: 0.0
    sampling_range:
      min: 0.0
      max: 50000.0

  - name: theta
    type_value: float
    default: 0.0
    sampling_range:
      min: -1.0
      max: 1.0

  - name: phi
    type_value: float
    default: 0.0
    sampling_range:
      min: -1.0
      max: 1.0

  - name: psi
    type_value: float
    default: 0.0
    sampling_range:
      min: -1.0
      max: 1.0

  - name: vel
    type_value: float
    default: 1.0
    sampling_range:
      min: 0.0
      max: 100.0

# Action-fluent variables
action_fluents:
  - name: set-acc
    type_value: float
    default: 0.0
    sampling_range:
      min: -1.0
      max: 1.0

  - name: set-phi
    type_value: float
    default: 0.0
    sampling_range:
      min: -1.0
      max: 1.0

  - name: set-theta
    type_value: float
    default: 0.0
    sampling_range:
      min: -1.0
      max: 1.0
